---
version: "3"

tasks:
  init:
    desc: Initialize streamlit app
    cmds:
      - poetry env use `which python 3.12`
      - poetry install
  run:
    desc: Run streamlit app
    cmds:
      - poetry run streamlit run template_streamlit/main.py
