---
version: "3"

tasks:
  init:
    desc: Initialize streamlit app
    cmds:
      - poetry env use `which python 3.12`
      - poetry add streamlit seaborn tqdm matplotlib altair pydantic plotly numpy pandas
      - poetry add --group lsp-dev pylsp-mypy python-lsp-server
      - poetry install
  remove:
    desc: Remove all previously installed dependencies
    cmds:
      - poetry env use `which python 3.12`
      - poetry remove streamlit seaborn tqdm matplotlib altair pydantic plotly numpy pandas
      - poetry remove --group lsp-dev pylsp-mypy python-lsp-server
  run:
    desc: Run streamlit app
    cmds:
      - poetry run streamlit run template_streamlit/main.py
