---
version: "3.8"

networks:
  default:
    name: template_streamlit

services:
  template_streamlit:
    build:
      context: ./Dockerfile
    container_name: template_streamlit_docker
    ports:
      - "80:8080"
    volumes:
      - ./:/app/
    environment:
      - TZ=Europe/Vienna
    command:
      - /bin/sh
      - -c
      - cd /app && tail -f /dev/null
